spring:
  mvc:
    servlet:
      path: /imagegram
  application:
    name: Imagegram
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  servlet:
    context-path: /api
